name       : kdewebkit
version    : 5.65.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/portingAids/kdewebkit-5.65.0.tar.xz : 82525a8fda1e9e2e7cde348b6e7227b0747f93d75a7648f4863e0e6889640586
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kio-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
