name       : kdewebkit
version    : 5.70.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/portingAids/kdewebkit-5.70.0.tar.xz : 08006cb81515fee4809b54fcfb4f9a2ed15d19c9bc85a49d5cedef69ff503279
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kio-devel
    - kparts-devel
    - kwallet-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
