name       : kdewebkit
version    : 5.60.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/portingAids/kdewebkit-5.60.0.tar.xz : bf16bf33dfdecc5e4e50bacc5ce142774c5c1522639d3d0042779734767f12fb
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kio-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
