name       : kdewebkit
version    : 5.43.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kdewebkit-5.43.0.tar.xz : cbc013f90b37bf0e4d5eee4204d0b7f3dce5e97679d32f7df8e75377ce6e277a
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kio-devel
    - kjobwidgets-devel
    - kparts-devel
    - kservice-devel
    - kwallet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
