name       : kdewebkit
version    : 5.41.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/kdewebkit-5.41.0.tar.xz : cdc8fd1b18822ab52c3e6dd269d148138c5adb17b44ec61b23b3f4332aedd1e6
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kio-devel
    - kjobwidgets-devel
    - kparts-devel
    - kservice-devel
    - kwallet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
