name       : kdewebkit
version    : 5.63.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/portingAids/kdewebkit-5.63.0.tar.xz : db78cf8b167562a211c20a081e23540d0613d2e6feec67d461bb9fc982ad6be8
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kio-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
