name       : kdewebkit
version    : 5.35.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.35/kdewebkit-5.35.0.tar.xz : b3c37554a68792e30d11a65140cb79e569bcced4375e42c7b91ad8a39fbad2fc
license    : LGPL-2.1
component  : programming
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kio-devel
    - kjobwidgets-devel
    - kparts-devel
    - kservice-devel
    - kwallet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
