name       : kdewebkit
version    : 5.93.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/portingAids/kdewebkit-5.93.0.tar.xz : a2fe9b5660763d4dd74244c00bf7b1a407438279a81f2a3ef3813ea250fd2f55
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5WebKit)
    - kparts-devel
    - ktextwidgets-devel
    - kwallet-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
