name       : kdewebkit
version    : 5.45.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/kdewebkit-5.45.0.tar.xz : e95dc228d0e0d7f3bbccde3349a8dd5e3621aa71dd3a617d09f7b5a7bd52bd49
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kio-devel
    - kjobwidgets-devel
    - kparts-devel
    - kservice-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
