name       : kdewebkit
version    : 5.47.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kdewebkit-5.47.0.tar.xz : a3f7060d9879ef2f3b3e49b979bf5d76db4e9acb8a12e20263c60ff09ba7e4f9
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kio-devel
    - kjobwidgets-devel
    - kparts-devel
    - kservice-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
