name       : kdewebkit
version    : 5.42.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/kdewebkit-5.42.0.tar.xz : 6ba25842d3cbd99c6816414e85fd7ff2d9dbde9fcde5c2faf3a74693d2254db3
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kio-devel
    - kjobwidgets-devel
    - kparts-devel
    - kservice-devel
    - kwallet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
