name       : kdewebkit
version    : 5.69.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/portingAids/kdewebkit-5.69.0.tar.xz : 1922d80c2398c9da4e8db8dc321eb6961cf55cf94b4918e137182c86251113d2
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kio-devel
    - kparts-devel
    - kwallet-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
