name       : kdewebkit
version    : 5.57.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/kdewebkit-5.57.0.tar.xz : 809e9df4ac3ca8b59799c8781694092cb1793f03af0b87a347a1c6019f96a592
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integration of the HTML rendering engine WebKit
description: |
    This library provides KDE integration of the QtWebKit library. If you are using QtWebKit in your KDE application, you are encouraged to use this layer instead of using the QtWebKit classes directly.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kio-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
